[project]
name = "embeddings-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "fastapi[all]>=0.116.1",
    "langchain-core>=0.3.76",
    "sentence-transformers>=5.1.0",
]
